/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SidekickCore {
  constructor()
  /** Load a flag directly into the in-memory cache */
  upsertFlag(key: string, isEnabled: boolean, rolloutPercentage?: number | undefined | null): void
  /** Evaluate a flag for a specific user */
  isEnabled(flagKey: string, userKey: string, userAttributes: Record<string, string>): boolean
}
